### ISSUE TITLE
strict argument in moment constructor

### ISSUE THREAD

**Issue by smmoosavi** [jalaali/moment-jalaali#15]
Salaam
In original `moment` constructor has 4 arguments. but in `moment-jalaali` get 3 arguments. Please add `strict` argument

See moment code: https://github.com/moment/moment/blob/develop/moment.js#L1736

**Comment by behrang** [comment]
Can you test if it is working or not? It should pass all other arguments to parrent moment constructor.

**Comment by me2bits** [comment]
+1
Please see https://github.com/moment/moment/blob/develop/moment.js#L888
When I use this code:
moment('1394-01-223 15:30:45', 'jYYYY-jMM-jDD HH:mm:ss', true).isValid()
it returns true!

**Comment by behrang** [comment]
Interesting. This also happens in `moment` itself.

The problem is that by specifying `jDD` (or `DD`), `moment` will extract 2 digits from input string, and validity depends on those two digits.

In your case, those two digits extracted from `223` is `22` which is a valid day of month. If it was `323` then it would be invalid.

So, either accept this behaviour or create an issue on `moment`, and link this one.

**Comment by me2bits** [comment]
No! in moment, valid function returns false. I check it (version : 2.8.1)
Please read this: http://stackoverflow.com/a/19979768

**Comment by behrang** [comment]
Check latest version, it should work.

**Comment by me2bits** [comment]
Thanks :-)
