### ISSUE TITLE
datetimepicker freezes the webpage

### ISSUE THREAD

**Issue by ali11reza** [jalaali/moment-jalaali#205]
hi,
tnx so much for the good work
I read other issues relating to my problem and find out that it's not an easy job and the datetimepicker.js should be modified in order to solve this but I don't know what to look for in the js file. I was just wondering if you could point me in the right direction. and how much time you think it takes to make datetimepicker use the Persian calendar??

**Comment by behrang** [comment]
`moment-jalali` adds Persian calendar support beside Gregorian calendar. So, in addition to `add(1, 'month')` there is also another unit, `jmonth`, and you can use `add(1, 'jmonth')`. Because of this, you have to change the date picker code, and convert everywhere that `month` is used, and instead use `jmonth`. Also, `year` should be replaced with `jyear`. This should give you a good start.

**Comment by ali11reza** [comment]
tnx so much
