### ISSUE TITLE
اشتباه تایپی

### ISSUE THREAD

**Issue by UKbed990** [jalaali/moment-jalaali#39]
با سلام.
گزارش یه مورد کوچیک:
تو لیست ماه ها ، ماه پنجم به جای "مرداد" نوشته شده: "امرداد"
(یعنی یه الف اولش اضافه داره)
با تشکر

**Comment by behrang** [comment]
https://fa.wikipedia.org/wiki/مرداد
https://fa.wikipedia.org/wiki/امرتات

**Comment by mehrdaad** [comment]
@behrang Is there option to provide the get the common name instead?

**Comment by behrang** [comment]
Yes, you can override it yourself. Also I think you can use the localization provided by the moment itself.

**Comment by mehrdaad** [comment]
Yeah but there should be some kind of option other than forking the repo since so many people want this.




On Thu, Aug 25, 2016 at 3:44 PM +0430, "Behrang Noruzi Niya" <notifications@github.com> wrote:





Yes, you can override it yourself. Also I think you can use the localization provided by the moment itself.

**Comment by behrang** [comment]
None of these two need forking the repository. Adding moment localization is just adding a dependency, and overridgin provided localization is a few lines of code in your project.

**Comment by mehrdaad** [comment]
you mean override original files in ``node_modules`` I don't think that would be a good solution.

**Comment by behrang** [comment]
No. Read moment docs about localizing to understand the API. Read [http://momentjs.com/docs/#/customization/](http://momentjs.com/docs/#/customization/) and [http://momentjs.com/docs/#/i18n/](http://momentjs.com/docs/#/i18n/).
