### ISSUE TITLE
Parse does-not work with Localized formats

### ISSUE THREAD

**Issue by MehdyKarimpour** [jalaali/moment-jalaali#60]
Hi guys,

In moment.js this works: 

``` JS
var moment = require("moment");
moment().format("L"); 
//"06/25/2016"

moment("06/25/2016", "L").toDate() 
//Sat Jun 25 2016 00:00:00 GMT+0430 (Iran Daylight Time)
```

but using moment-jalaali parsing localized formats doesn't:

``` JS
var moment = require("moment");
moment().format("L"); 
//"1395/04/05"

moment("1395/04/05", "L").toDate()  //<----- error!
//Sat Jan 01    0 00:00:00 GMT+0330 (Iran Standard Time)
```

Would you please help us.

Best Regards
Mehdy Karimpour

**Comment by behrang** [comment]
In moment, `L` is a shortcut for `MM/DD/YYYY` or something like that. `moment-jalaali` does not change the behaviour of `MM` or `DD` or `YYYY`. Instead, there are few other format tokens like `jMM`, `jDD` or `jYYYY` which are used.

In your case, if you want to use `L`, you need to first define it as for example `jYY/jM/jD` and then use it.

**Comment by MehdyKarimpour** [comment]
Thanks for your reply,

1. How can we define L to be jYY/jM/jD by default in persian?
2.Why it works for format but not for parse?

Best Regards
Mehdy

**Comment by behrang** [comment]
Based on your example, I thought you did not load Persian locale. But it seems that you have loaded it. In that case `L` token is set to correct Jalaali tokens. The problem is that when parsing, input format is not converted to a longer format and so it is not handled in `moment-jalaali` and is passed to `moment`. 

Although it is useful to be able to parse input with locale specific formats, it needs a lot of work and I think the alternative to use more specific format tokens is easy enough. So for now, please don't use `L` and its friends.
